name: CSC2503
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=6.1.1=h2a67f75_3
  - filelock=3.20.0=py312h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - fsspec=2025.10.0=py312h7040dfc_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py312h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.5.0=py312h06a4308_0
  - jinja2=3.1.6=py312h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.8.2=h3ec8f01_0
  - libavif=1.1.1=h5eee18b_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.4=h77a78f3_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnsl=2.0.0=h5eee18b_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.30=h46f56fc_0
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.7.0=hde9077f_0
  - libtorch=2.5.1=cpu_openblas_h526855f_4
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py312h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.5=py312h06a4308_0
  - nomkl=3.0=0
  - numpy=2.3.4=py312h816806e_1
  - numpy-base=2.3.4=py312h7203c5b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.0.18=hd6dcaed_0
  - opentelemetry-api=1.37.0=py312h06a4308_0
  - pcre2=10.46=hf426167_0
  - pillow=12.0.0=py312h3b88751_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-global=2.13.6=py312hdb19cb5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - sqlite=3.51.0=h2a70700_0
  - sympy=1.14.0=py312h06a4308_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - typing-extensions=4.15.0=py312h06a4308_0
  - typing_extensions=4.15.0=py312h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zipp=3.21.0=py312h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - beautifulsoup4==4.14.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - clip==1.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - dassl==0.4.2
      - entrypoints==0.3
      - fire==0.7.1
      - flake8==3.7.9
      - fonttools==4.60.1
      - ftfy==6.3.1
      - future==1.0.0
      - gdown==5.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - humanize==4.14.0
      - idna==3.11
      - imageio==2.37.2
      - isort==4.3.21
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markdown==3.10
      - matplotlib==3.10.7
      - mccabe==0.6.1
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cufile-cu12==1.14.1.1
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.9.79
      - packaging==25.0
      - point-e==0.0.0
      - protobuf==6.33.0
      - pybind11==3.0.1
      - pycodestyle==2.5.0
      - pyflakes==2.1.1
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - six==1.17.0
      - soupsieve==2.8
      - tb-nightly==2.21.0a20251023
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - torch==2.8.0+cu129
      - torch-scatter==2.1.2+pt28cu129
      - torchaudio==2.8.0+cu129
      - torchvision==0.23.0+cu129
      - tqdm==4.67.1
      - triton==3.4.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - yacs==0.1.8
      - yapf==0.29.0
prefix: /u/yyuntian/store/miniconda/envs/CSC2503
